config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new', as: 'login'
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy", as: 'logout'
  resources :recommendations
  resources :shop_reviews
  resources :shops, only: [:index, :show, :new, :create]
  resources :teas, only: :show
  resources :users, except: :index
  root :to => "sessions#new"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recommendation.rb
class Recommendation < ApplicationRecord
    belongs_to :user
    belongs_to :tea
    validates :comments, length: { in: 10..100 }
end

app/models/shop.rb
class Shop < ApplicationRecord
    has_many :shop_reviews
    has_many :teas
    has_many :users, through: :shop_reviews

    def shop_with_location
        "#{self.name} - #{self.location}"
    end

    def ratings
        self.shop_reviews.map {|review| review.rating}
    end 

    def avg_rating
        (self.ratings.sum.to_f / self.ratings.length).round(2)
    end 
    
end

app/models/shop_review.rb
class ShopReview < ApplicationRecord
    belongs_to :user
    belongs_to :shop
    validates :shop_id, uniqueness: { scope: :user_id, message: "has already been reviewed!" }
    validates :rating, inclusion: { in: 1..5, message: "has to be between 1 and 5." }
    validates :review, length: { in: 10..100 }



end

app/models/tea.rb
class Tea < ApplicationRecord
    belongs_to :shop
    has_many :recommendations
    has_many :users, through: :recommendations

    def tea_with_shop
        "#{self.name} - #{Shop.find_by(id: self.shop_id).name}"
    end 

    def shop_and_location
        "#{self.name} - #{Shop.find_by(id: self.shop_id).name} - #{Shop.find_by(id: self.shop_id).location}"
    end

end

app/models/user.rb
class User < ApplicationRecord
    has_many :recommendations
    has_many :shop_reviews
    has_many :shops, through: :shop_reviews
    has_many :teas, through: :recommendations
    has_secure_password
    validates :username, presence: true
    validates :username, uniqueness: true
    validates :password, presence: true
    validates :first_name, presence: true
    validates :last_name, presence: true

    def full_name
        "#{self.first_name} #{self.last_name}"
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticated
    helper_method :logged_in?


    private

    def current_user
        @current_user = User.find_by(id: session[:user_id])
    end

    def logged_in?
        !current_user.nil?
    end

    def authenticated
        redirect_to login_path unless logged_in?
    end
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
  before_action :set_recommendation, only: [:show, :edit, :update, :destroy]


  def index
    @recommendations = @current_user.recommendations
  end


  def show
  end


  def new
    @recommendation = Recommendation.new
  end

 
  def edit
  end


  def create
    recommendation = Recommendation.create(recommendation_params.merge(user_id: @current_user.id))
    if recommendation.valid?
      redirect_to recommendations_path
    else
      flash[:errors] = recommendation.errors.full_messages
      redirect_to new_recommendation_path
    end
  end


  def update
    @recommendation.update(recommendation_params)
    if @recommendation.valid?
      redirect_to recommendations_path
    else
      flash[:errors] = @recommendation.errors.full_messages
      redirect_to edit_recommendation_path
    end
  end


  def destroy
    @recommendation.destroy
    redirect_to recommendations_path
  end

  private
    
    def set_recommendation
      @recommendation = Recommendation.find(params[:id])
    end

    def recommendation_params
      params.require(:recommendation).permit(:user_id, :tea_id, :comments)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticated, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(username: params[:username])
    
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      flash[:errors] = ["Incorrect Username or Password"]
      redirect_to login_path
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to login_path
  end
end

app/controllers/shop_reviews_controller.rb
class ShopReviewsController < ApplicationController
  before_action :set_shop_review, only: [:show, :edit, :update, :destroy]


  def index
    @shop_reviews = @current_user.shop_reviews
  end


  def show
  end
  
  
  def new
    @shop_review = ShopReview.new
  end


  def edit
  end


  def create
    shop_review = ShopReview.create(shop_review_params.merge(user_id: @current_user.id))
    if shop_review.valid?
      redirect_to shop_review_path(shop_review)
    else
      flash[:errors] = shop_review.errors.full_messages
      redirect_to new_shop_review_path
    end
  end


  def update
    @shop_review.update(shop_review_params)
    if @shop_review.valid?
      redirect_to shop_reviews_path
    else
      flash[:errors] = @shop_review.errors.full_messages
      redirect_to edit_shop_review_path
    end
  end


  def destroy
    @shop_review.destroy
    redirect_to shop_reviews_path
  end

  private
    def set_shop_review
      @shop_review = ShopReview.find(params[:id])
    end

    def shop_review_params
      params.require(:shop_review).permit(:user_id, :shop_id, :rating, :review)
    end
end

app/controllers/shops_controller.rb
 class ShopsController < ApplicationController
  # skip_before_action :authenticated, only: [:index]
  before_action :set_shop, only: [:show, :edit, :update, :destroy]


  def index
    # byebug
    if params[:search_term]
      key = params["Search by"]
      @shops = Shop.where("#{key} like ?", "%#{params[:search_term].titleize}%")
      if @shops == []
        @shops = Shop.all
      end
    else
      @shops = Shop.all
    end
  end


  def show
    
  end


  def new
    @shop = Shop.new
  end

  def create
    @shop = Shop.new(shop_params)

  end

  private
    def set_shop
      @shop = Shop.find(params[:id])
    end

    def shop_params
      params.require(:shop).permit(:name, :location, :address)
    end

    def filtering_params(params)
      params.slice(:starts_with, :location)
    end
end

app/controllers/teas_controller.rb
class TeasController < ApplicationController
  before_action :set_tea, only: [:show, :edit, :update, :destroy]


  def index
    @teas = Tea.all
  end


  def show
  end



  private
    def set_tea
      @tea = Tea.find(params[:id])
    end

    def tea_params
      params.require(:tea).permit(:name, :price, :img_url, :shop_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticated, only: [:new, :create]

  def show
    
  end


  def new
    @user = User.new
  end


  def edit
  end

  def create
    @user = User.create(user_params)
    if @user.valid?
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_path
    end
  end


  def update
    @user.update(user_params)
    if @user.valid?
      redirect_to user_path(@user)
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to edit_user_path(@user)
    end
  end


  def destroy
    @user.destroy
    render new_user_path
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:username, :password, :first_name, :last_name, :photo_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recommendations_helper.rb
module RecommendationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shop_reviews_helper.rb
module ShopReviewsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/teas_helper.rb
module TeasHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html style="background: #172f43;">
  <head>
    <title>BubbleUp! App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <% javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  
  <body style="background: #172f43;">
  
    <nav class="navbar" role="navigation" aria-label="main navigation", style="background-color: #0FB2FE;
    min-height: 3.25rem;
    position: relative;
    z-index: 30;">
      <div class="navbar-brand">
        <img src="https://cdn2.iconfinder.com/data/icons/bubble-milk-tea/500/bubble-tea-drink_9-512.png" width="112" height="28">
      </div>

    <% if logged_in? %>
      <div class="navbar-end">
        <div class="navbar-item">
          <div class="buttons">
                <h1 style="font-size: 25px">
                <strong>
                  Welcome, <%= @current_user.full_name %>
                </strong>
                </h1>
              <a class="button-is-primary">
                <strong>
                  <%= button_to "Logout", "/logout", method: :delete, class:"button-is-primary" %>
                </strong>
              </a>
          </div>
        </div>
      </div>

    <% else %>

      <div class="navbar-end">
        <div class="navbar-item">
          <div class="buttons">
              <a class="button is-link" href=<%= new_user_path %>>
                <strong>
                  Sign Up
                </strong>
              </a>
              <a class="button is-light" href=<%= login_path %>>
                Login
              </a>
          </div>
        </div>
      </div>
    <% end %>
  
  </nav>

    <%= yield %>

  </body>
</html>

app/views/recommendations/_form.html.erb
<% if flash[:errors] %>
  <div id="error_explanation" style="font-weight: bold;">
    <h2><%= pluralize(flash[:errors].count, "error") %>
      prohibited this recommendation from being saved:
    </h2>
      
      <% flash[:errors].each do |message| %>
        <p style="color: black;">
          <%= message %>
        </p>
      <% end %>

  </div>
<% end %>

<%= form_for @recommendation do |form| %>
   <div class="select is-multiple">
   <%= form.label "Tea", class: "label"%>
   <%= form.collection_select :tea_id, Tea.all, :id, :shop_and_location, prompt: true, class: "input"%> 
  </div>

  <div class="field">
    <%= form.label :comments, class: "label"%>
    <%= form.text_field :comments, class: "input"%>
  </div>

  <div class="button">
    <%= form.submit "Submit Recommendation", class: "button-is-primary"%>
  </div>
<% end %>

app/views/recommendations/edit.html.erb
<h1 class= "label" style="background-color: #011F2E; color: #fff;">
  <strong style="color: #fff;">
    New Recommendation
  </strong>
</h1>

<br>

<%= render 'form', recommendation: @recommendation %>

<br>

<h1>
  <%= link_to 'Back to Recommendations', recommendations_path %>
</h1>

app/views/recommendations/index.html.erb
<h1 class= "label" style="background-color: #011F2E; color: #fff;">
  <strong style="color: #fff;">
    My Recommendations
  </strong>
</h1>

<div class="container" style="display: flex; justify-content: center">
  <table class="table">
    <thead>
      <tr class="is-selected">
        <th class="row">
          Tea
        </th>
        <th class="row">
          Comments
        </th>
        <th class="row" colspan="3"></th>
      </tr>
    </thead>

    <tbody>

    <% @recommendations.each do |recommendation| %>
        <tr>
          <td class="row-content">
            <p>
              <%= link_to Tea.find(recommendation.tea_id).tea_with_shop, tea_path(Tea.find(recommendation.tea_id)) %>
            </p>
          </td>
          <td class="row-content">
            <p>
              <%= recommendation.comments %>
            </p>
          </td>
          <td class="row-content">
            <p>
              <%= link_to 'Edit', edit_recommendation_path(recommendation) %>
            </p>
          </td>
          <td class="row-content">
            <p>
              <%= button_to 'Delete Recommendation', recommendation, method: :delete, class:"button-is-primary" %>
            </p>
          </td>
        </tr>
      <% end %>

    </tbody>
  </table>
</div>

<br>

<div class="container" style="display: flex; justify-content: center">
  <h1>
    <%= link_to 'Add a Recommendation', new_recommendation_path %> |
    <%= link_to 'Back to User', user_path(@current_user) %>
  </h1>
</div>

app/views/recommendations/new.html.erb
<h1 class= "label" style="background-color: #011F2E; color: #fff;">
    New Recommendation
</h1>

<br>

<%= render 'form', recommendation: @recommendation %>

<br>

<h1>
    <%= link_to 'Back to User', user_path(@current_user) %>
</h1>

app/views/recommendations/show.html.erb
<h1 class= "label" style="background-color: #011F2E; color: #fff;">
  <strong style="color: #fff;">
    Current Recommendation
  </strong>
</h1>

<p>
  <strong>
    User: <%= @recommendation.user_id %>
  </strong>
</p>

<p>
  <strong>
    Tea: <%= @recommendation.tea_id %>
  </strong>
</p>

<p>
  <strong>
    Comments: <%= @recommendation.comments %>
  </strong>
</p>

<h1>
  <%= link_to 'Edit', edit_recommendation_path(@recommendation) %> |
  <%= link_to 'Back', recommendations_path %>
</h1>

app/views/shop_reviews/_form.html.erb
<% if flash[:errors] %>
  <div id="error_explanation" style="font-weight: bold;">
    <h2><%= pluralize(flash[:errors].count, "error") %>
      prohibited this review from being saved:
    </h2>

      <% flash[:errors].each do |message| %>
        <p style="color: black;">
          <%= message %>
        </p>
      <% end %>

  </div>
<% end %>

<%= form_for @shop_review do |form| %>
   <div class="select is-multiple">
   <%= form.label "Shop", class: "label"%>
   <%= form.collection_select :shop_id, Shop.all, :id, :shop_with_location, prompt: true, class: "input"%> 
  </div>

  <div class="field">
    <%= form.label :rating, class: "label"%>
    <%= form.number_field :rating, class: "input"%>
  </div>

  <div class="field">
    <%= form.label :review, class: "label"%>
    <%= form.text_field :review, class: "input"%>
  </div>

  <div class="button">
    <%= form.submit 'Submit Review', class: "button-is-primary" %>
  </div>
<% end %>

app/views/shop_reviews/edit.html.erb
<h1 class= "label" style="background-color: #011F2E; color: #fff;">
  <strong style="color: #fff;">
    Editing Shop Review
  </strong>
</h1>

<%= render 'form', shop_review: @shop_review %>

<br>

<h1>
  <%= link_to 'Back', shop_reviews_path %>
</h1>

app/views/shop_reviews/index.html.erb
<h1 class= "label" style="background-color: #011F2E; color: #fff;">
  <strong style="color: #fff;">
    Shop Reviews
  </strong>
</h1>

<div class="container" style="display: flex; justify-content: space-around">
  <table class="table">
    <thead>
      <tr class="is-selected">
        <th class="row">
          Shop
        </th>
        <th class="row">
          Rating
        </th>
        <th class="row">
          Review
        </th>
        <th class="row" colspan="3"></th>
      </tr>
    </thead>

    <tbody>

      <% @shop_reviews.each do |shop_review| %>
        <tr>
          <td class="row-content">
            <h1>
              <%= link_to Shop.find(shop_review.shop_id).shop_with_location, shop_review_path(Shop.find(shop_review.shop_id)) %>
            </h1>
          </td>
          <td class="row-content">
            <h1>
              <%= shop_review.rating %>
            </h1>
          </td>
          <td class="row-content">
            <h1>
              <%= shop_review.review %>
            </h1>
          </td>
          <td class="row-content">
            <h1>
              <%= link_to 'Edit', edit_shop_review_path(shop_review) %>
            </h1>
          </td>
          <td class="row-content">
            <h1>
              <%= button_to 'Delete Review', shop_review, method: :delete, class: "button-is-primary" %>
            </h1>
          </td>
        </tr>
      <% end %>

    </tbody>
  </table>
</div>

<br>

<div class="container" style="display: flex; justify-content: space-around;">
  <h1>
    <%= link_to 'Review a Shop', new_shop_review_path %> |
    <%= link_to 'Back to User', user_path(@current_user) %>
  </h1>
</div>

app/views/shop_reviews/new.html.erb
<h1 class= "label" style="background-color: #011F2E; color: #fff;">
  <strong style="color: #fff;">
    New Shop Review
  </strong>
</h1>

<%= render 'form', shop_review: @shop_review %>

<br>

<h1>
  <%= link_to 'Back', shop_reviews_path %>
</h1>

app/views/shop_reviews/show.html.erb
<h1 class= "label" style="background-color: #011F2E; color: #fff;">
  <strong>
    Shop Review
  </strong>
</h1>

<div style="display: flex; justify-content: center">
  <div class="has-text-justified" style="display: block; margin-left: auto; margin-right: auto; ">
    <p>
      <strong>
        Shop: <%= Shop.find(@shop_review.shop_id).name %>
      </strong>
    </p>

    <p>
      <strong>
        Rating: <%= @shop_review.rating %>
      </strong>
    </p>

    <p>
      <strong>
        Review: <%= @shop_review.review %>
      </strong>
    </p>

    <br>

    <h1>
      <%= link_to 'Edit', edit_shop_review_path(@shop_review) %> |
      <%= link_to 'Back', shop_reviews_path %>
    </h1>
  </div>
</div>

app/views/shops/_form.html.erb
<% if flash[:errors] %>
  <div id="error_explanation" style="font-weight: bold;">
    <h2><%= pluralize(flash[:errors].count, "error") %> prohibited this review from being saved:</h2>
      <% flash[:errors].each do |message| %>
        <p style="color: black;"><%= message %></p>
      <% end %>
  </div>
<% end %>

<%= form_for @shop do |form| %>
  <div class="field">
    <%= form.label :name, class: "label" %>
    <%= form.text_field :name, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :location, class: "label" %>
    <%= form.text_field :location, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :address, class: "label" %>
    <%= form.text_field :address, class: "input" %>
  </div>

  <div class="button" >
    <%= form.submit 'Submit Shop', class: "button-is-primary" %>
  </div>
<% end %>

app/views/shops/edit.html.erb
<h1 class= "label" style="background-color: #011F2E; color: #fff;">
    <strong style="color: #fff;">Editing Shop</strong>
</h1>

<%= render 'form', shop: @shop %>

<br>

<h1>
    <%= link_to 'Show', @shop %> |
    <%= link_to 'Back', shops_path %>
</h1>

app/views/shops/index.html.erb
<h1 class= "label" style="background-color: #011F2E; color: #fff;">
  <strong style="color: #fff;">Shops</strong>
</h1>


<%= form_tag "/shops", method: :get do %>
  <div class="field">
    <%= select_tag "Search by", options_for_select([["location", "location"],["name", "name"]]), class: "label", style:"color:black;"%>
    <%= text_field_tag :search_term, nil, class: "input" %>
    <%= submit_tag "Filter for Shop", class: "button-is-primary"%>
  </div>
<% end %>


<% if @shops %>
  <div class="container" style="display: flex; justify-content: center">
    <table class="table">
      <thead>
        <tr class="is-selected">
          <th class="row">
            Average Rating
          </th>
          <th class="row">
            Name
          </th>
          <th class="row">
            Location
          </th>
          <th class="row">
            Address
          </th>
          <th class="row" colspan="3"></th>
        </tr>
      </thead>

      <tbody>

        <% @shops.each do |shop| %>

          <tr>
            <td class="row-content">
              <h1>
                <%= shop.avg_rating %>
              </h1>
            </td>
            <td class="row-content">
              <h1>
                <%= shop.name %>
              </h1>
            </td>
            <td class="row-content">
              <h1>
                <%= shop.location %>
              </h1>
            </td>
            <td class="row-content">
              <h1>
                <%= shop.address %>
              </h1>
            </td>
            <td class="row-content">
              <h1>
                <%= link_to 'Show', shop %>
              </h1>
            </td>
          </tr>

        <% end %>

      </tbody>
    </table>
</div>

<% else %>


<div class="container" style="display: flex; justify-content: center">
  <h2>
    Shop could not be found!
  </h2>
  <%= link_to 'Back to Shops', shops_path %>
</div>

<% end %>

  <br>

<div class="container" style="display: flex; justify-content: center">
  <% if logged_in? %>
    <h1>
      <%= link_to 'New Shop', new_shop_path %> |
      <%= link_to 'Back to User', user_path(@current_user) %>
    </h1>
  <% end %>
</div>

app/views/shops/new.html.erb
<h1 class= "label" style="background-color: #011F2E; color: #fff;">
    <strong>
        New Shop
    </strong>
</h1>

<%= render 'form', shop: @shop %>

<br>

<h1>
    <%= link_to 'Back', shops_path %>
</h1>

app/views/shops/show.html.erb
<h1 class= "label" style="background-color: #011F2E; color: #fff;">
  <strong>Current Shop</strong>
</h1>

  <div style="display: flex; justify-content: center">
    <div class="has-text-justified" style="display: block; margin-left: auto; margin-right: auto; ">
      <p>
        <strong>
          Name: <%= @shop.name %>
        </strong>
      </p>
      <p>
        <strong>
          Location: <%= @shop.location %>
        </strong>
      </p>
      <p>
        <strong>
          Address: <%= @shop.address %>
        </strong>
      </p>
      <p>
        <strong>
          Average Rating: <%= @shop.avg_rating %>
        </strong>
      </p>
    </div>
  </div>

<br>

<br>

  <div class="container" style="display: flex; justify-content: space-around">
    <table class="table" style="width: 300px;">
      <thead>
        <tr class="is-selected">
          <th class= "row">
            Tea Menu:
          </th>
        </tr>
      </thead>

      <tbody>
      <% @shop.teas.each do |tea| %>
        <tr>
          <td class="row-content">
            <p>
              <%= link_to tea.name, tea_path(tea) %>
            </p>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>

    <table class="table" style="width: 700px;">
      <thead>
        <tr class="is-selected">
          <th class="row">
            Reviews:
          </th>
        </tr>
      </thead>

      <tbody>

      <% @shop.shop_reviews.each do |review| %>

        <tr>
          <td class="row-content">
            <p>
              Rating: <%= "#{review.rating} - #{review.review}" %>
            </p>
          </td>
        </tr>

      <% end %>

      </tbody>

    </table>

  </div>

<br>

<div class="container" style="display: flex; justify-content: center">
  <h1>
    <%= link_to 'Back', shops_path %>
  </h1>
</div>

app/views/teas/show.html.erb
<h1 class= "label" style="background-color: #011F2E; color: #fff;">
  <strong style="color: #fff;">
    Current Tea
  </strong>
</h1>

<p style="text-align:center;">
  <img class="is-rounded" width="300" height="300" src=<%= @tea.img_url %> />
</p>

<br>

<div style="text-align: center;">
  <p>
    <h1 style="font-size: 20px;">
      <strong>
        Name: <%= @tea.name %>
      </strong>
    </h1>
  </p>

  <br>

  <p>
    <h1 style="font-size: 20px;">
      <strong>
        Price: <%= "$#{@tea.price}" %>
      </strong>
    </h1>
  </p>

  <br>

  <p>
    <h1 style="font-size: 20px;">
      <strong>
        Shop: <%= Shop.find(@tea.shop_id).name %>
      </strong>
    </h1>
  </p>

  <br>

  <p>
    <h1 style="font-size: 20px;">
      <strong>
        Location: <%= Shop.find(@tea.shop_id).location %>
      </strong>
    </h1>
  </p>

  <br>

  <p>
    <h1>
      <%= link_to 'Back to Shop', shop_path(Shop.find(@tea.shop_id)) %> |
      <%= link_to 'Back to Recommendations', recommendations_path %>
    </h1>
  </p>
</div>

app/views/users/_form.html.erb
<% if flash[:errors] %>
  <div id="error_explanation" style="font-weight: bold;">
    <h2>
      <%= pluralize(flash[:errors].count, "error") %>
        prohibited this user from being saved:
    </h2>
    
    <% flash[:errors].each do |message| %>
      <p style="color: black;">
        <%= message %>
      </p>
    <% end %>

  </div>
<% end %>

<%= form_for @user do |form| %>
  <div class="field">
    <%= form.label :username, class: "label"%>
    <%= form.text_field :username, class: "input"%>
  </div>

  <div class="field">
    <%= form.label :password, class: "label"%>
    <%= form.password_field :password, class: "input"%>
  </div>

  <div class="field">
    <%= form.label :first_name, class: "label"%>
    <%= form.text_field :first_name, class: "input"%>
  </div>

  <div class="field">
    <%= form.label :last_name, class: "label"%>
    <%= form.text_field :last_name, class: "input"%>
  </div>

  <div class="field">
    <%= form.label :photo_url, class: "label"%>
    <%= form.text_field :photo_url, class: "input"%>
  </div>

  <div class="button">
    <%= form.submit 'Submit User', class: "button-is-primary" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1 class= "label" style="background-color: #011F2E; color: #fff;">
    <strong style="color: #fff;">
        Editing User
    </strong>
</h1>

<%= render 'form', user: @user %>

<br>

<h1>
    <%= link_to 'Show', @user %> |
    <%= link_to 'Back', user_path(@user) %>
</h1>

app/views/users/new.html.erb
<h1 class= "label" style="background-color: #011F2E; color: #fff;">
    <strong style="color: #fff;">
        New User
    </strong>
</h1>

<br>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<h1 class= "label" style="background-color: #011F2E; color: #fff;">
  <strong style="color: #fff;">
    Current User
  </strong>
</h1>

<div style="text-align: center;">

  <% if params[:id].to_i != @current_user.id %>
    <p>
      <img class="is-rounded" width="275" height="275" src=<%= @user.photo_url %> />
    </p>

    <p>
      <h1 style="font-size: 20px;">
        <strong>
          Name: <%= @user.full_name %>
        </strong>
      </h1>
    </p>

    <br>

    <h1>
      <%= link_to 'Back to User', user_path(@current_user) %>
    </h1>

  <% else%>

    <p>
      <img class="is-rounded" width="275" height="275" src=<%= @user.photo_url %> />
    </p>
    
    <p>
      <h1 style="font-size: 20px;">
        <strong>
          Name: <%= @user.full_name %>
        </strong>
      </h1>
    </p>

    <br>

    <%= button_to 'Edit', edit_user_path(@user), method: :get, class: "button-is-primary" %> 
    <%= button_to 'Delete User', user_path(@user), method: :delete, class: "button-is-primary" %>

    <br>

    <h1>
      <strong>
        <%= link_to 'View Boba Shops', shops_path%> |
        <%= link_to 'My Reviews', shop_reviews_path %> |
        <%= link_to 'My Recommendations', recommendations_path %>
      </strong>
    </h1>
  <% end %> 

</div>